on:
  pull_request:
  push:

name: Validate Install

jobs:

  package_linux_release:
    name: Package Linux Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Polaris
      uses: actions/checkout@v1
    - name: Download Polaris Web
      run: |
        curl -L -o web.zip https://github.com/agersant/polaris-web/releases/latest/download/web.zip
        unzip web.zip
    - name: Read Polaris Version
      run: echo ::set-env name=POLARIS_VERSION::${GITHUB_REF:10}
    - name: Build Archive
      run: res/unix/release_script.sh
    - name: Upload packaged release
      uses: actions/upload-artifact@v2
      with:
        name: linux-release
        path: release

  validate_linux_system_install:
    name: Linux System Install
    runs-on: ubuntu-latest
    needs: package_linux_release

    steps:
    - name: Download release
      uses: actions/download-artifact@v2
      with:
        name: linux-release
        path: .
    - name: Extract release
      run: tar -xzvf *.tar.gz --strip-components=1
    - name: Preview Install
      run: make preview
    - name: Preview Install w/ Custom Prefix
      run: make preview PREFIX=/some/random/prefix
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        profile: minimal
        default: true
    - name: Install
      run: sudo --preserve-env=PATH make install
    - name: Uninstall
      run: sudo make uninstall

  validate_linux_xdg_install:
    name: Linux XDG Install
    runs-on: ubuntu-latest
    needs: package_linux_release

    steps:
    - name: Download release
      uses: actions/download-artifact@v2
      with:
        name: linux-release
        path: .
    - name: Extract release
      run: tar -xzvf *.tar.gz --strip-components=1
    - name: Preview Install
      run: make preview-xdg
    - name: Preview Install w/ Custom XDG_DATA_HOME
      run: make preview-xdg XDG_DATA_HOME=/my/own/xdg/home
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        profile: minimal
        default: true
    - name: Install
      run: make install-xdg
    - name: Uninstall
      run: make uninstall-xdg
